- back-end/sls/go.mod
- back-end/sls/go.sum
- back-end/sls/payments/main.go
> refactor: serverless에서 분리한 패키지 import

- back-end/pkg/abs/history.go
- back-end/pkg/abs/slack.go
- back-end/pkg/abs/slack_test.go
- 슬랙 메시지의 텍스트를 Payment 구조체로 변환하는 기능
- history 함수
> feat: 슬랙 메시지의 텍스트를 Payment 구조체로 변환하는 기능

- back-end/.gitignore
- back-end/sls/Makefile
- back-end/sls/go.mod
- back-end/sls/go.sum
- back-end/sls/serverless.yml
- #14 
- sls 프레임워크 go 플러그인 적용
- x86 -> arm64
- AWS 리전 변경 : 서울 -> 도쿄
- AWS 서울 리전은 람다 arm64 아키텍처를 지원 ❌
> update: 아키텍처, aws 리전 변경

- back-end/sls/serverless.yml
- sls 프레임워크의 api gateway 설정 변경
- private 키 설정 -> 헤더에 'x-api-key' 포함 해야됨
- api.choshsh.com 도메인 연결
> update: API GW 변경 httpApi -> restApi

- back-end/pkg/abs/history.go
- back-end/pkg/abs/slack_test.go
- #19 
- 슬랙에서 메시지 가져오는 API
- 범위 : start <= 데이터 < end
- start 형식: yyyy-MM
- end 형식 : yyyy-MM
> feat: 날짜 범위 검색 기능

- back-end/sls/Makefile
- back-end/sls/go.mod
- back-end/sls/go.sum
- back-end/sls/payments/main.go
- back-end/sls/serverless.yml
- aws lambda api 업데이트
- queryString 날짜 변수로 데이터 기간 필터링
> update: queryString으로 날짜 필터 기능 추가

- .github/workflows/ci.yml
> feat: CI/CD 구성

- front-end/.env
- front-end/.env.development
- front-end/src/common/Api.js
- #28 
- `.env`, `.env.development` 파일을 추가함
- get 요청 url 부분을 수정함
> add: .env 파일 생성하기

- .gitignore
- back-end/sls/serverless.yml
- #30 
- [노션 링크](https://j2e4.notion.site/CORS-4e0cb0988c854ae39b724fa4d85da4c0)
- AWS API Gateway CORS 설정 변경
> Feat cors 처리

- front-end/src/App.css
- front-end/src/App.js
- front-end/src/components/PaymentListView.css
- front-end/src/components/PaymentListView.js
- front-end/src/components/SummaryBySign.css
- front-end/src/components/SummaryBySign.js
- #32
- [React Fragments](https://ko.reactjs.org/docs/fragments.html)
- main 영역을 추가했다.
- 가져온 월별 전체 내역 데이터를 일별로 구분해서 보여준다.
> 32 feat 결제 내역 데이터 가져오기 2차

- .github/workflows/backend-cicd.yml
- .github/workflows/codeql.yml
- .github/workflows/frontend-cicd.yml
- back-end/Makefile
- #41 
- [serverless 액션 GitHub 링크](https://github.com/serverless/github-action)
- backend 배포 자동화
- frontend CI/CD 파이프라인 이름 변경
> feat: backend cicd 구성

- .github/workflows/backend-cicd.yml
- #41 
- https://github.com/serverless/serverless/issues/8800
- backend CI/CD 스크립트
> fix: serverless/github-action@v3가 sub-directory를 지원하지 않는 문제

- front-end/public/index.html
- front-end/src/App.css
- front-end/src/components/PaymentListView.css
- #49 
- [MDN - position](https://developer.mozilla.org/en-US/docs/Web/CSS/position)
- [Stack Overflow](https://stackoverflow.com/a/70001634)
- 모바일 웹으로 볼 때 스크롤이 두 개 생겨서 불편하던 문제를 해결했다.
- meta태그 `theme-color`를 페이지 배경색과 맞춰서 전체 화면이 통일성 있게 보이도록 수정했다.
> 49 modify 헤더를 고정하는 방식 수정하기

- front-end/src/App.js
- front-end/src/common/useRequest.js
* custom hook을 만들었다.
- #52 
- processing state와 response data를 반환하는 custom hook 생성
- 다른 곳에서도 재사용할 수 있길 기대하며 만들었다.
> refactor: Api 요청을 하는 custom hook 만들기

- front-end/src/App.css
- front-end/src/App.js
- front-end/src/common/ErrorContext.js
- front-end/src/common/useRequest.js
- front-end/src/components/ErrorLogger.js
- #45 
- [Axios Docs - Handling Errors](https://axios-http.com/docs/handling_errors)
- [React Bootstrap - Toasts](https://react-bootstrap.github.io/components/toasts/)
- [React - Context](https://ko.reactjs.org/docs/context.html)
- [React - useContext](https://ko.reactjs.org/docs/hooks-reference.html#usecontext)
- [TOAST UI: 리액트 앱에서의 중앙 집중식 API 에러 핸들링](https://ui.toast.com/weekly-pick/ko_20200623)
- #54 에서 남겨뒀던 TODO를 개발하고 @choshsh님이 리뷰를 통해 제안해주신 내용을 적용했다.
- aside 영역을 추가하고 에러가 발생했을 경우 aside 안에서 Toast로 보여준다.
> fix: api response에 대한 에러 처리하기

- front-end/yarn.lock
- #68 
- CVE-2021-3803
- 지우기만 했어요.
> security: nth-check

- .github/workflows/backend-cicd.yml
- back-end/Makefile
- #75 
- serverless cli docs: https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy
- backend aws 배포 변경
- 설정 변경 시, AWS 리소스 전체 배포
- 소스 코드 변경 시, lambda 함수만 배포
> ci: serverless 배포 효율화

- back-end/go.mod
- back-end/go.sum
- 의존성 전체 업그레이드
- go.mod, go.sum
> ci: upgrade all go module

- front-end/package.json
- front-end/src/index.js
- front-end/src/routes/Test.jsx
- front-end/yarn.lock
- #78 
- [React Router - Tutorial](https://reactrouter.com/docs/en/v6/getting-started/tutorial)
- [SPA 에서 SEO 적용하기 :: 마이구미](https://mygumi.tistory.com/385)
- React Router를 추가했다.
- 기존에 보여주던 main 페이지를 `/` 경로로 할당했다.
> 78: add react router

- back-end/internal/abs/group.go
- back-end/internal/abs/group_test.go
- back-end/internal/abs/payment.go
- back-end/internal/abs/payment_test.go
- back-end/internal/abs/router.go
- back-end/internal/abs/user.go
- back-end/internal/abs/user_test.go
- #85 
- group payment method api 구현
> 85: feat group payment method api 구현

- .github/workflows/frontend-cicd.yml
- front-end/.env.development
- front-end/.gitignore
- front-end/src/pages/Login.jsx
- #95 
- `REACT_APP_`으로 시작하게 변경
- ci/ci 스크립트 수정
> 95: 구글 클라이언트 id 참조 변수 수정하기

- .github/workflows/backend-cicd.yml
- back-end/serverless.yml
- #97 
- serverless 설정 문서 (https://www.serverless.com/framework/docs/providers/aws/events/apigateway#enabling-cors)
- serverless cors 설정
> fix: cors 이슈

- .github/workflows/backend-cicd.yml
- back-end/controller/payment_c.go
- back-end/pkg/slack/slack_test.go
- back-end/router/router.go
- back-end/service/group_s.go
- back-end/service/payment_s.go
- back-end/service/user_s.go
- #93 
- Mongo 조인 (https://github.com/Kamva/mgm#aggregation)
- payement API
- 버그 수정
- 슬랙 데이터 -> 몽고DB 마이그레이션
> feat: 결제 데이터 api

- back-end/cmd/app.go
- back-end/controller/payment_c.go
- back-end/service/payment_s.go
- #101 
- Payment API 조회 API 파라미터 방식 변경
- order by 파라미터는 추후에 추가할게요
> fix: http body json 파라미터를 QueryString 파라미터로 변경

- front-end/package.json
- front-end/src/App.js
- front-end/src/pages/MainApp.jsx
* Router의 Link를 써야한다고 함.
- #105 
- https://stackoverflow.com/questions/54843302/reactjs-bootstrap-navbar-and-routing-not-working-together
- https://react-bootstrap.github.io/components/navs/#nav-link-props
- Bootstramp Component `Nav.Link`에 `as` prop 설정
- 경로 Navigate하던 거 삭제했다. 좀 더 알아보고 추가하려구..
- 새로고침했을 때 404 에러나는 현상은 좀 더 찾아보자
> fix: react-router 라우팅 안 되는 문제 해결하기

- back-end/serverless.yml
- back-end/util/error_handler.go
- front-end/src/App.js
- front-end/src/App.scss
- front-end/src/pages/GroupListView.jsx
- front-end/src/pages/GroupListView.scss
- front-end/src/pages/MainApp.jsx
- front-end/src/pages/MainApp.scss
- front-end/src/pages/PaymentRegisterView.jsx
- front-end/src/pages/PaymentRegisterView.scss
- #110 
- 내역을 등록할 수 있는 화면을 추가했어요.
- 꼭 필요한 입력 값을 입력하지 않았을 경우 등록할 수 없어요.
- 입력을 완료했을 경우 이전 화면으로 되돌아가요.
- 실행 중 에러가 발생했을 때 에러를 보여주고 있지 않아요. 빠른 시일 내에 에러를 보여주도록 수정할꺼에요. 😢
> 내역 등록 기능 추가하기

- back-end/service/payment_s.go
- #119 
- 참고 문서: go mgm 문서 (https://github.com/Kamva/mgm#usage:~:text=%7D%2C%20book)-,Update%20a%20document,-//%20Find%20your%20book)
- 결제내역 수정 API
- 파라미터로 받은 Payment 구조체로 바로 업데이트 했었는데 에러
- 수정: 파라미터로 받은 ID로 조회한 Payment 구조체를 변경하고 업데이트하도록 처리
> fix: 결제내역 업데이트

- front-end/src/common/Common.scss
- front-end/src/pages/PaymentListView.jsx
- front-end/src/pages/PaymentListView.scss
- front-end/src/pages/PaymentRegisterView.jsx
- #117 
- customizing bootstrap style
- able to modify payment item you registered
- fix bug unable to register monthly installment
> 등록한 거래 내역 추가할 수 있게 하기

- back-end/controller/group_c.go
- back-end/router/router.go
- back-end/service/group_s.go
- #125 
- golang mgm (https://github.com/Kamva/mgm#usage)
- 그룹 삭제 API 추가
> feat: group 삭제 API

- front-end/src/App.js
- front-end/src/common/useRouterNavigateWith.js
- front-end/src/pages/GroupListView.jsx
- front-end/src/pages/GroupRegisterView.jsx
- front-end/src/pages/GroupRegisterView.scss
- front-end/src/pages/MainApp.jsx
> feat: 그룹 추가할 수 있게 하기
